ALTER TABLE users ADD COLUMN IF NOT EXISTS gstn VARCHAR(15);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS job_title VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS billing_address TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS about TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS pan VARCHAR(10);
ALTER TABLE users ADD COLUMN IF NOT EXISTS license_type VARCHAR(20) DEFAULT 'free';
